Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

Load the Dataset

In [3]:
dataset = "/content/student_performance.csv"

student = pd.read_csv(dataset)

student.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

Understand the Dataset

In [4]:
print("Dataset Shape:", student.shape)
print("No of Rows:", student.shape[0])
print("No of Columns:", student.shape[1])

Dataset Shape: (1000000, 6)
No of Rows: 1000000
No of Columns: 6

In [5]:
print("\nColumn Names:")
print(student.columns)

Column Names:
Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

In [6]:
print("\nDataset Information:")
print(student.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 45.8+ MB
None

In [7]:
print("\nStatistical Summary:")
student.describe().transpose()

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
student_id,1000000.0,500000.500000,288675.278933,1.0,250000.75,500000.5,750000.25,1000000.0
weekly_self_study_hours,1000000.0,15.029127,6.899431,0.0,10.30,15.0,19.70,40.0
attendance_percentage,1000000.0,84.711046,9.424143,50.0,78.30,85.0,91.80,100.0
class_participation,1000000.0,5.985203,1.956421,0.0,4.70,6.0,7.30,10.0
total_score,1000000.0,84.283845,15.432969,9.4,73.90,87.5,100.00,100.0

Check Dataset Issues

In [8]:
print("\nMissing Values:")
print(student.isnull().sum())

print("\nDuplicate Rows:")
print(student.duplicated().sum())

Missing Values:
student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

Duplicate Rows:
0

Standardize Column Names

In [9]:
student.columns = (
    student.columns
    .str.strip()
    .str.replace(' ', '_')
    .str.replace(r'[%()]', '', regex=True)
)

print(student.columns)

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

Handle Invalid Values

In [10]:
print("Minimum Study Hours:",
      student['weekly_self_study_hours'].min())

print("Maximum Study Hours:",
      student['weekly_self_study_hours'].max())

Minimum Study Hours: 0.0
Maximum Study Hours: 40.0

In [11]:
print("Minimum Attendance:",
      student['attendance_percentage'].min())

print("Maximum Attendance:",
      student['attendance_percentage'].max())

Minimum Attendance: 50.0
Maximum Attendance: 100.0

In [12]:
print("Minimum Class Participation:",
      student['class_participation'].min())

print("Maximum Class Participation:",
      student['class_participation'].max())

Minimum Class Participation: 0.0
Maximum Class Participation: 10.0

In [13]:
print("Minimum Total Score:",
      student['total_score'].min())

print("Maximum Total Score:",
      student['total_score'].max())

Minimum Total Score: 9.4
Maximum Total Score: 100.0

Check Missing Values

In [14]:
print(student.isnull().sum())

student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

Remove Unnecessary Columns

In [15]:
student = student.drop(columns=['student_id'])

print(student.columns)

Index(['weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

Remove Duplicate Records

In [16]:
print("Number of duplicate rows:",
      student.duplicated().sum())

student = student.drop_duplicates()

print("Shape after removing duplicates:",
      student.shape)

Number of duplicate rows: 17868
Shape after removing duplicates: (982132, 5)

Encode Categorical Variables

In [18]:
le = LabelEncoder()

student['grade'] = le.fit_transform(student['grade'])

student.head()

,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,18.5,95.6,3.8,97.9,0
1,14.0,80.0,2.5,83.9,1
2,19.5,86.3,5.3,100.0,0
3,25.7,70.2,7.0,100.0,0
4,13.4,81.9,6.9,92.0,0

Separate Features and Target

In [20]:
X = student.drop('grade', axis=1)
y = student['grade']

Split the Dataset into Training and Testing Data

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (785705, 4)
X_test : (196427, 4)
y_train: (785705,)
y_test : (196427,)

Feature Scaling

In [22]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Verify the Preprocessed Data

In [23]:
print("Training data shape:", X_train_scaled.shape)
print("Testing data shape :", X_test_scaled.shape)

Training data shape: (785705, 4)
Testing data shape : (196427, 4)

In [24]:
print("\nMissing values in X_train:")
print(X_train.isnull().sum().sum())

Missing values in X_train:
0

In [25]:
print("\nMissing values in X_test:")
print(X_test.isnull().sum().sum())

Missing values in X_test:
0

In [26]:
print("\nFirst 5 rows of scaled training data:")
print(X_train_scaled[:5])

First 5 rows of scaled training data:
[[ 0.08573893 -1.05297033  1.48748705  1.03613751]
 [-0.17585194  0.72891244 -0.24588358 -0.70134642]
 [-0.2630489   0.89963175  1.07963514  0.16739554]
 [-2.16684914 -1.57579821 -2.48906909 -1.22648149]
 [-0.8152963   1.64652872 -0.95962442 -0.11786301]]

Save the Cleaned Dataset

In [27]:
student.to_csv(
    "cleaned_student_performance.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [28]:
cleaned_student = pd.read_csv(
    "cleaned_student_performance.csv"
)

print("Cleaned Dataset Shape:",
      cleaned_student.shape)

print(cleaned_student.head())

Cleaned Dataset Shape: (982132, 5)
   weekly_self_study_hours  attendance_percentage  class_participation  \
0                     18.5                   95.6                  3.8
1                     14.0                   80.0                  2.5
2                     19.5                   86.3                  5.3
3                     25.7                   70.2                  7.0
4                     13.4                   81.9                  6.9

   total_score  grade
0         97.9      0
1         83.9      1
2        100.0      0
3        100.0      0
4         92.0      0